### ISSUE TITLE
netstandard 2.0 support

### ISSUE THREAD

**Issue by symbiogenesis** [zcsizmadia/ZCS.DataContractResolver#55]
Could this be added as a target? I think this project should support all targets that STJ supports.

**Comment by zcsizmadia** [comment]
Netstandard2.0 support was removed about 5 months ago when I enabled the latest C# 12 language features. What is the use case for requiring netstandard2.0?

**Comment by symbiogenesis** [comment]
I was considering adding this library as a dependency in [Dotmim.Sync](https://github.com/Mimetis/Dotmim.Sync)

**Comment by symbiogenesis** [comment]
netstandard2.0 enables .NET Framework 4.x support, and the end of life for those is very far out.

**Comment by zcsizmadia** [comment]
Let me revert those original changes when I removed netstandard support. Some language features might need to be removed or ifdef'd.

**Comment by zcsizmadia** [comment]
fyi v1.0.3 has the netstandard support (https://www.nuget.org/packages/ZCS.DataContractResolver/1.0.3).

I will make a new PR, since there is some trickery with the package versioning and how to test the netstandard generated library. However you can start to use the 1.0.3 version and move to the latest once it is pushed to nuget.

**Comment by zcsizmadia** [comment]
v1.2.0 is pushed to nuget (/w netstandard2.0 enabled again).  https://www.nuget.org/packages/ZCS.DataContractResolver/1.2.0
